---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pv-claim
  labels:
    app: postgres
spec:
  storageClassName: 'rook-cephfs'
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      securityContext: {}
      containers:
        - name: postgres
          image: ahemida96/iriswebapp_db
          securityContext: {}
          resources: {}
          imagePullPolicy: "IfNotPresent"

          env:

          - name: POSTGRES_DB  # Setting Database name
            value: iris_db

          - name: POSTGRES_USER  # Setting Database username
            value: postgres

          - name:  POSTGRES_PASSWORDD # Setting Database password
            value: postgres

          - name:  POSTGRES_ADMIN_USER # Setting Database admin user 
            value: raptor

          - name:  POSTGRES_ADMIN_PASSWORD # Setting Database admin password 
            value: postgres

          - name:  POSTGRES_PORT # Setting Database port
            value: "5432"

          - name: POSTGRES_HOST_AUTH_METHOD
            value: trust

          ports:
            - containerPort: 5432

          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgredb
      volumes:
        - name: postgredb
          persistentVolumeClaim:
            claimName: postgres-pv-claim

---

apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  type: ClusterIP
  ports:
   - port: 5432
  selector:
   app: postgres
---  
